#!/bin/zsh

alias cl="clear && colorscript random" 
alias cc="z ~/.clones"
alias cd.="z ~/.config"
alias cd="z"
alias Fucknm="sudo systemctl restart NetworkManager"
alias gc="git clone --depth 1"
alias shit="sudo shutdown now"
alias fucked="sudo systemctl suspend"
alias live="sudo auto-cpufreq --live"
alias re="sudo reboot"
alias aud="alsamixer"
alias ls='exa -al --color=always --group-directories-first' # my preferred listing
alias la='exa -a --color=always --group-directories-first'  # all files and dirs
alias ll='exa -l --color=always --group-directories-first'  # long format
alias lt='exa -aT --color=always --group-directories-first' # tree listing
alias lsd='exa -ld --color=always --group-directories-first' # tree listing
alias sudoedit="sudo nvim"
alias nv="nvim"
alias rmf="rm -rf"
alias srmf="sudo rm -rf"
alias car="cargo run"
alias sp="sudo pacman"
alias pp="paru"
alias cool="sudo intel-undevolt apply"
alias Render="kitty +kitten icat"
alias godHelpme="sudo chown -R  kvl:users"
alias yay="paru"
